apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: ${CLOUD_RUN_JOB_NAME}
spec:
  template:
    spec:
      template:
        spec:
          serviceAccountName: ${JOB_RUNTIME_SERVICE_ACCOUNT}
          maxRetries: 1
          timeoutSeconds: 900
          containers:
            - image: ${IMAGE_URI}
              command:
                - /app/daily-news-job
              resources:
                limits:
                  cpu: '1'
                  memory: 1Gi
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: DATABASE_URL
                      key: latest
                - name: GOOGLE_CSE_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: GOOGLE_CSE_API_KEY
                      key: latest
                - name: GOOGLE_CSE_ID
                  valueFrom:
                    secretKeyRef:
                      name: GOOGLE_CSE_ID
                      key: latest
                - name: YOUTUBE_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: YOUTUBE_API_KEY
                      key: latest
                - name: GOOGLE_CSE_DATE_RESTRICT
                  value: m1
