#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "Daily News · Neon + GCP setup"

stage "GCP project and Artifact Registry"
open_url "https://console.cloud.google.com/home/dashboard"
step "Select your GCP project, then enable Cloud Run, Artifact Registry, Secret Manager, IAM Credentials, and Security Token Service APIs."
step "Create a Docker Artifact Registry repository in asia-east1 (for example: daily-news)."
ask GCP_PROJECT_ID "GCP project ID (for example daily-news):"
ask GCP_REGION "Cloud Run region [asia-east1]:"
GCP_REGION="${GCP_REGION:-asia-east1}"
ask ARTIFACT_REPOSITORY "Artifact Registry repository name:"
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
write_env GCP_REGION "$GCP_REGION"
write_env ARTIFACT_REPOSITORY "$ARTIFACT_REPOSITORY"
pause "Press Enter after the APIs and repository exist."

stage "Neon database and GCP secrets"
open_url "https://console.neon.tech/app/projects"
step "Open your Neon project, choose Connect, and copy the PostgreSQL connection string with its sslmode parameters unchanged."
ask_secret DATABASE_URL "Paste Neon DATABASE_URL (hidden):"
ask_secret ALLOWED_USER_EMAIL "Paste the one allowed Google email (hidden):"
write_env DATABASE_URL "$DATABASE_URL"
write_env ALLOWED_USER_EMAIL "$ALLOWED_USER_EMAIL"
if confirm "Create/update DATABASE_URL and ALLOWED_USER_EMAIL in Secret Manager now?"; then
  for secret_name in DATABASE_URL ALLOWED_USER_EMAIL; do
    gcloud secrets describe "$secret_name" --project "$GCP_PROJECT_ID" >/dev/null 2>&1 || gcloud secrets create "$secret_name" --replication-policy=automatic --project "$GCP_PROJECT_ID"
    printf '%s' "${!secret_name}" | gcloud secrets versions add "$secret_name" --data-file=- --project "$GCP_PROJECT_ID"
  done
else
  SKIPPED+=("Secret Manager: DATABASE_URL and ALLOWED_USER_EMAIL")
fi

stage "Firebase Google Sign-In"
open_url "https://console.firebase.google.com/"
step "Create or select the Firebase project linked to this app."
step "Authentication → Sign-in method → Google → Enable; register the Android and iOS apps if they are not already registered."
step "Do not create a Firebase Admin key. Cloud Run uses Application Default Credentials."
pause "Press Enter after Google Sign-In is enabled."

stage "Cloud Run runtime identities"
open_url "https://console.cloud.google.com/iam-admin/serviceaccounts"
step "Create daily-news-api and daily-news-ingestion service accounts."
step "Grant each identity Secret Manager Secret Accessor only on its needed secrets."
step "Grant daily-news-api permission to execute the Job with overrides (Cloud Run Developer on that Job)."
pause "Press Enter after both runtime service accounts and grants exist."

stage "GitHub Workload Identity Federation"
open_url "https://console.cloud.google.com/iam-admin/workload-identity-pools"
step "Create a global workload identity pool and GitHub OIDC provider. Use issuer https://token.actions.githubusercontent.com/."
step "Map google.subject=assertion.sub and repository attributes; restrict the condition to your owner/repository and deployment branch."
step "Create a dedicated GitHub deployer service account and grant the restricted federated principal Workload Identity User."
ask GCP_WORKLOAD_IDENTITY_PROVIDER "Full WIF provider resource name:"
ask GCP_SERVICE_ACCOUNT "GitHub deployer service-account email:"
write_env GCP_WORKLOAD_IDENTITY_PROVIDER "$GCP_WORKLOAD_IDENTITY_PROVIDER"
write_env GCP_SERVICE_ACCOUNT "$GCP_SERVICE_ACCOUNT"

stage "GitHub Actions Variables"
ask CLOUD_RUN_JOB_NAME "Cloud Run Job name [daily-news-ingestion]:"
CLOUD_RUN_JOB_NAME="${CLOUD_RUN_JOB_NAME:-daily-news-ingestion}"
write_env CLOUD_RUN_JOB_NAME "$CLOUD_RUN_JOB_NAME"
step "The script will set only non-secret GitHub Variables in the current gh repository."
if confirm "Set the five GitHub Variables now?"; then
  set_var GCP_PROJECT_ID "$GCP_PROJECT_ID"
  set_var GCP_REGION "$GCP_REGION"
  set_var GCP_WORKLOAD_IDENTITY_PROVIDER "$GCP_WORKLOAD_IDENTITY_PROVIDER"
  set_var GCP_SERVICE_ACCOUNT "$GCP_SERVICE_ACCOUNT"
  set_var CLOUD_RUN_JOB_NAME "$CLOUD_RUN_JOB_NAME"
else
  SKIPPED+=("GitHub Variables")
fi

stage "Review before deployment"
open_url "https://console.cloud.google.com/run"
step "Confirm the API service name is daily-news-api and the Job name matches CLOUD_RUN_JOB_NAME."
step "Confirm GitHub Actions has id-token: write and uses WIF, never a service-account key."
warn "Run the deploy workflow only after reviewing the generated .env values locally. Do not commit that file."
pause "Press Enter to finish."

finish
